plugins:
  - fp
  - import
parser: babel-eslint
env:
  es6: true
  node: true
  browser: true
extends:
 - airbnb-base
 - plugin:fp/recommended
rules:
  fp/no-nil: off
  fp/no-unused-expression: off
  fp/no-mutation: off
  fp/no-let: off
  no-use-before-define: off
  import/prefer-default-export: off
  no-param-reassign: off
  key-spacing:
    - error
    -
      align: value
  semi:
    - error
    - never
