plugins:
  - fp
  - lodash-fp
  - ramda
  - prefer-arrow
env:
  es6: true
  node: true
  jest: true
extends:
  - airbnb-base
  - plugin:fp/recommended
  - plugin:lodash-fp/recommended
  - plugin:ramda/recommended
  - plugin:eslint-comments/recommended
rules:
  eslint-comments/no-unused-disable: error
  fp/no-nil: off
  fp/no-let: off
  fp/no-unused-expression: off
  fp/no-mutation: off
  no-use-before-define: off
  no-param-reassign: off
  no-unexpected-multiline: error
  newline-per-chained-call:
    - error
    -
      ignoreChainWithDepth: 1
  func-call-spacing:
    - error
    - never
  semi:
    - error
    - never
  key-spacing:
    - error
    -
      align: value
  prefer-arrow/prefer-arrow-functions:
    - error
