version: '3'
services:
    redis:
        image: 'redis:latest'

    backend:
        image: 'node:11.11'
        working_dir: /tails/backend
        command: ["sh", "./run-dev.sh"]
        volumes:
          - ./backend:/tails/backend
          - ./common:/tails/common
          - ./signaling:/tails/signaling
        environment:
            - CORS_WHITELIST=${CORS_WHITELIST}
            - GAME_CODE=${GAME_CODE}
            - REDIS_URL=${REDIS_URL}
            - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
            - VERSION=${VERSION}
        ports:
            - '3000:3000'

    game:
        image: 'node:11.11'
        working_dir: /tails/game
        command: ["sh", "./run-dev.sh"]
        volumes:
            - ./game:/tails/game
            - ./common:/tails/common
            - ./signaling:/tails/signaling
        ports:
            - '8081:8081'
        environment:
            - CONTROLLER_URL=${CONTROLLER_URL}
            - ERROR_LOGGING=${ERROR_LOGGING}
            - HTTP_ADDRESS=${HTTP_ADDRESS}
            - VERSION=${VERSION}
            - WS_ADDRESS=${WS_ADDRESS}

    controller:
        image: 'node:11.11'
        working_dir: /tails/controller
        command: ["sh", "./run-dev.sh"]
        volumes:
          - ./controller:/tails/controller
          - ./common:/tails/common
          - ./signaling:/tails/signaling
        environment:
            - REACT_APP_ERROR_LOGGING=${REACT_APP_ERROR_LOGGING}
            - REACT_APP_VERSION=${REACT_APP_VERSION}
            - REACT_APP_WS_ADDRESS=${REACT_APP_WS_ADDRESS}
        ports:
            - '4001:4001'
