version: '3'
services:
    redis:
        image: 'redis:latest'

    backend:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - '3000:3000'
            - '3001:3001'
        depends_on:
            - redis

    game:
        build:
            context: .
            dockerfile: ./game/Dockerfile
        ports:
            - '8081:8081'

    controller:
        environment:
            - REACT_APP_WS_ADDRESS=ws://localhost:3000
        build:
            context: .
            dockerfile: ./controller/Dockerfile
        ports:
            - '4001:4001'
