version: '2'
services:
    redis:
        image: 'redis:latest'
        logging:
          driver: awslogs
          options: 
            awslogs-group: tutorial
            awslogs-region: us-east-1
            awslogs-stream-prefix: wordpress

    backend:
        image: 'rymdkraftverk/novelty_backend'
        logging:
          driver: awslogs
          options: 
            awslogs-group: tutorial
            awslogs-region: us-east-1
            awslogs-stream-prefix: wordpress
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - redis

    game:
        image: 'rymdkraftverk/novelty_game'
        logging:
          driver: awslogs
          options: 
            awslogs-group: tutorial
            awslogs-region: us-east-1
            awslogs-stream-prefix: wordpress
        build:
            context: ./
            dockerfile: ./game/Dockerfile
        ports:
            - '8081:8081'

    controller:
        image: 'rymdkraftverk/novelty_controller'
        logging:
          driver: awslogs
          options: 
            awslogs-group: tutorial
            awslogs-region: us-east-1
            awslogs-stream-prefix: wordpress
        build:
            context: ./
            dockerfile: ./controller/Dockerfile
        ports:
            - '3001:3001'
