version: '3'
services:
    game:
        image: 'node:11.11'
        working_dir: /tails/game
        command: ["sh", "./run-dev.sh"]
        volumes:
            - ./game:/tails/game
            - ./common:/tails/common
        ports:
            - '8081:8081'
        environment:
            - CONTROLLER_URL=${CONTROLLER_URL}
            - ERROR_LOGGING=${ERROR_LOGGING}
            - HTTP_ADDRESS=${HTTP_ADDRESS}
            - VERSION=${VERSION}
            - WS_ADDRESS=${WS_ADDRESS}

    controller:
        image: 'node:11.11'
        working_dir: /tails/controller
        command: ["sh", "./run-dev.sh"]
        volumes:
          - ./controller:/tails/controller
          - ./common:/tails/common
        environment:
            - REACT_APP_ERROR_LOGGING=${REACT_APP_ERROR_LOGGING}
            - REACT_APP_VERSION=${REACT_APP_VERSION}
            - REACT_APP_WS_ADDRESS=${REACT_APP_WS_ADDRESS}
        ports:
            - '4001:4001'
