version: '3'
services:
    backend:
        image: 'node:carbon'
        working_dir: /novelty/backend
        command: ["sh", "./run-dev.sh"]
        volumes:
            - ./backend:/novelty/backend
            - ./common:/novelty/common

    game:
        image: 'node:carbon'
        working_dir: /novelty/game
        command: ["sh", "./run-dev.sh"]
        volumes:
            - ./game:/novelty/game
            - ./common:/novelty/common

    controller:
        image: 'node:carbon'
        working_dir: /novelty/controller
        command: ["sh", "./run-dev.sh"]
        volumes:
            - ./controller:/novelty/controller
            - ./common:/novelty/common
