version: '3'
services:
    redis:
        ports:
            - '6379:6379'

    backend:
        image: 'node:carbon'
        working_dir: /novelty/backend
        command: ["sh", "./run-dev.sh"]
        volumes:
            - ./backend:/novelty/backend
            - ./common:/novelty/common

    game:
        image: 'node:carbon'
        working_dir: /novelty/game
        command: ["sh", "./run-dev.sh"]
        volumes:
            - ./game:/novelty/game
            - ./common:/novelty/common

    controller:
        image: 'node:carbon'
        working_dir: /novelty/controller
        command: ["sh", "./run-dev.sh"]
        volumes:
            - ./controller:/novelty/controller
            - ./common:/novelty/common
        environment:
            - REACT_APP_WS_ADDRESS=ws://localhost:3000
