version: '3'
services:
    redis:
        image: 'redis:latest'

    influxdb:
        image: 'influxdb:latest'
        ports:
            - '8086:8086'
        environment:
            - INFLUXDB_DB=novelty
        volumes:
            - $PWD/docker/influxdb/data:/var/lib/influxdb

    grafana:
        image: 'grafana/grafana:latest'
        ports:
            - '5000:3000'
        environment:
            - -e 'GF_INSTALL_PLUGINS=briangann-gauge-panel, grafana-piechart-panel, natel-plotly-panel, natel-influx-admin-panel, vonage-status-panel'
        volumes:
            - $PWD/docker/grafana/data:/var/lib/grafana

    backend:
        environment:
            - REDIS_PATH=rs://redis:6379
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - '3000:3000'
            - '3001:3001'
        depends_on:
            - redis

    game:
        build:
            context: .
            dockerfile: ./game/Dockerfile
        ports:
            - '8081:8081'
        environment:
            - WS_ADDRESS=${WS_ADDRESS}
            - HTTP_ADDRESS=${HTTP_ADDRESS}

    controller:
        environment:
            - REACT_APP_WS_ADDRESS=${REACT_APP_WS_ADDRESS}
        build:
            context: .
            dockerfile: ./controller/Dockerfile
        ports:
            - '4001:4001'
