version: '3'
services:
    redis:
        image: 'redis:latest'

    backend:
        environment:
            - REDIS_PATH=rs://redis:6379
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - '3000:3000'
            - '3001:3001'
        depends_on:
            - redis

    game:
        build:
            context: .
            dockerfile: ./game/Dockerfile
        ports:
            - '8081:8081'
        environment:
            - WS_ADDRESS=${WS_ADDRESS}
            - HTTP_ADDRESS=${HTTP_ADDRESS}

    controller:
        environment:
            - REACT_APP_WS_ADDRESS=${REACT_APP_WS_ADDRESS}
        build:
            context: .
            dockerfile: ./controller/Dockerfile
        ports:
            - '80:4001'
