version: '3'
services:
    backend:
        image: 'node:carbon'
        working_dir: /tails/backend
        command: ["sh", "./run-dev.sh"]
        volumes:
            - ./backend:/tails/backend
            - ./common:/tails/common
            - ./signaling:/tails/signaling

    game:
        image: 'node:carbon'
        working_dir: /tails/game
        command: ["sh", "./run-dev.sh"]
        volumes:
            - ./game:/tails/game
            - ./common:/tails/common
            - ./signaling:/tails/signaling

    controller:
        image: 'node:carbon'
        working_dir: /tails/controller
        command: ["sh", "./run-dev.sh"]
        volumes:
            - ./controller:/tails/controller
            - ./common:/tails/common
            - ./signaling:/tails/signaling
