version: '3'
services:
    redis:
        image: 'redis:latest'

    backend:
        environment:
            - REDIS_PATH=rs://redis:6379
            - GAME_CODE=${GAME_CODE}
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - redis

    game:
        build:
            context: .
            dockerfile: ./game/Dockerfile
        ports:
            - '8081:8081'
        environment:
            - WS_ADDRESS=${WS_ADDRESS}
            - HTTP_ADDRESS=${HTTP_ADDRESS}
            - ERROR_LOGGING=${ERROR_LOGGING}
            - CONTROLLER_URL=${CONTROLLER_URL}

    controller:
        environment:
            - REACT_APP_WS_ADDRESS=${REACT_APP_WS_ADDRESS}
            - REACT_APP_ERROR_LOGGING=${REACT_APP_ERROR_LOGGING}
        build:
            context: .
            dockerfile: ./controller/Dockerfile
        ports:
            - '4001:4001'
