plugins:
  - import
  - react
parser: babel-eslint
env:
  browser: true
rules:
  react/jsx-uses-vars: error
  react/jsx-uses-react: error
  react/no-this-in-sfc: error
  fp/no-this: off
  fp/no-let: off
  import/prefer-default-export: off
