---
processors:
- stylelint-processor-styled-components
syntax: scss
extends:
- stylelint-config-standard
- stylelint-config-styled-components
rules:
  declaration-empty-line-before: null
  max-empty-lines: null
  rule-empty-line-before: null
