---
customSyntax: postcss-styled-syntax
extends:
- stylelint-config-standard
rules:
  declaration-empty-line-before: null
  font-family-name-quotes: null
  font-family-no-missing-generic-family-keyword: null
  rule-empty-line-before: null
